In [3]:
import pandas as pd
import numpy as np
import netCDF4 as nc

os.environ['TZ'] = 'UTC'

In [372]:
doi = "2021-07-26"

y_oi = doi.split('-')[0]
m_oi = doi.split('-')[1]
d_oi = doi.split('-')[2]

# Get tobac tracking data
fname = "/Volumes/Elements/data/tobac/Save/"+y_oi+"/"+m_oi+"/"+d_oi+"/Track.nc"
ds = nc.Dataset(fname)

frame = ds.variables['frame'][:]
idx = ds.variables['idx'][:]
hdim_1 = ds.variables['hdim_1'][:]
hdim_2 = ds.variables['hdim_2'][:]
num = ds.variables['num'][:]
threshold_value = ds.variables['threshold_value'][:]
feature = ds.variables['feature'][:]
time = ds.variables['time'][:]
timestr = ds.variables['timestr'][:]
latitude = ds.variables['latitude'][:]
longitude = ds.variables['longitude'][:]
cell = ds.variables['cell'][:]
time_cell = ds.variables['time_cell'][:]

data = pd.DataFrame({'frame':frame, 'idx': idx, 'hdim_1':hdim_1, 'hdim_2':hdim_2,
'num':num, 'threshold_value': threshold_value, 'feature': feature, 'time':time,'timestr':timestr, 'latitude': latitude, 'longitude':longitude, 'cell':cell, 'time_cell':time_cell})

# delete all rows where data.cell is NaN
# these rows are not connected to an individual object
#data = data.dropna(subset = ['cell'])

In [387]:
no = 2
cell_data = pd.DataFrame()

In [380]:
temp = data[(data.timestr == "2021-07-26 11:09:52") & np.isnan(data.cell) & (data.latitude > 48.24) & (data.latitude < 48.25)]
temp = temp.reset_index(drop=True)
#temp = pd.DataFrame([temp.loc[1]])
temp

,frame,idx,hdim_1,hdim_2,num,threshold_value,feature,time,timestr,latitude,longitude,cell,time_cell
0,25,422,485.6985,369.648104,20,220,7863,7552,2021-07-26 11:09:52,48.245075,8.519317,NaN,NaN

In [393]:
temp = data[data.cell == 755]
temp = temp.reset_index(drop=True)
#temp = pd.DataFrame([temp.loc[1]])
#temp = temp.loc[1:2]
temp

,frame,idx,hdim_1,hdim_2,num,threshold_value,feature,time,timestr,latitude,longitude,cell,time_cell
0,6,219,510.585386,215.927193,40,250,1872,1792,2021-07-26 09:33:52,48.403541,7.051680,755.0,0.0
1,7,231,517.557442,219.823241,140,250,2167,2176,2021-07-26 09:40:16,48.447846,7.088877,755.0,384.0
2,8,316,526.358571,224.572919,28,240,2533,2432,2021-07-26 09:44:32,48.503720,7.134224,755.0,640.0
3,9,315,534.443976,228.660001,32,240,2821,2688,2021-07-26 09:48:48,48.554996,7.173245,755.0,896.0
4,10,318,542.565652,234.181321,64,240,3117,3072,2021-07-26 09:55:12,48.606449,7.225959,755.0,1280.0
5,11,313,550.539626,240.711841,66,240,3411,3328,2021-07-26 09:59:28,48.656913,7.288309,755.0,1536.0
6,12,319,558.708669,245.727919,79,240,3715,3584,2021-07-26 10:03:44,48.708562,7.336199,755.0,1792.0
7,13,354,567.102985,248.989628,207,240,4047,3968,2021-07-26 10:10:08,48.761579,7.367341,755.0,2176.0
8,14,333,577.019550,253.211593,310,240,4362,4224,2021-07-26 10:14:24,48.824136,7.407649,755.0,2432.0
9,15,339,584.676270,258.054373,345,240,4679,4480,2021-07-26 10:18:40,48.872385,7.453885,755.0,2688.0
10,16,409,591.545878,259.867221,70,230,5063,4864,2021-07-26 10:25:04,48.915633,7.471193,755.0,3072.0
11,17,401,597.744176,263.322918,131,230,5371,5120,2021-07-26 10:29:20,48.954622,7.504186,755.0,3328.0
12,18,399,594.174755,263.346023,200,230,5686,5376,2021-07-26 10:33:36,48.932172,7.504407,755.0,3584.0
13,19,398,597.455021,266.213702,184,230,5997,5760,2021-07-26 10:40:00,48.952804,7.531786,755.0,3968.0
14,20,400,598.240768,267.311844,348,230,6306,6016,2021-07-26 10:44:16,48.957744,7.542270,755.0,4224.0
15,21,395,599.159959,270.412788,378,230,6622,6272,2021-07-26 10:48:32,48.963522,7.571876,755.0,4480.0
16,22,414,601.620887,273.758732,523,230,6942,6656,2021-07-26 10:54:56,48.978993,7.603821,755.0,4864.0
17,23,402,604.328274,276.908938,500,230,7235,6912,2021-07-26 10:59:12,48.996005,7.633898,755.0,5120.0
18,24,418,607.081200,280.284136,578,230,7552,7296,2021-07-26 11:05:36,49.013297,7.666122,755.0,5504.0
19,25,406,611.599064,282.038652,490,230,7848,7552,2021-07-26 11:09:52,49.041664,7.682873,755.0,5760.0
20,26,406,615.822530,284.737186,705,230,8149,7808,2021-07-26 11:14:08,49.068169,7.708637,755.0,6016.0
21,27,408,620.946835,288.574325,759,230,8444,8192,2021-07-26 11:20:32,49.100306,7.745272,755.0,6400.0
22,28,432,624.364419,293.781632,942,230,8755,8448,2021-07-26 11:24:48,49.121726,7.794988,755.0,6656.0
23,29,415,629.411944,298.381200,895,230,9053,8704,2021-07-26 11:29:04,49.153349,7.838902,755.0,6912.0
24,30,419,633.946582,302.157585,850,230,9365,9088,2021-07-26 11:35:28,49.181737,7.874957,755.0,7296.0
25,31,421,639.872349,304.160430,1033,230,9676,9344,2021-07-26 11:39:44,49.218814,7.894079,755.0,7552.0
26,32,440,632.872985,313.341728,136,230,10001,9600,2021-07-26 11:44:00,49.175020,7.981737,755.0,7808.0

In [394]:
cell_data = pd.concat([cell_data,temp], axis = 0)
cell_data = cell_data.reset_index(drop=True)

In [395]:
cell_data.to_csv("/Users/nicobader/Documents/Uni_Leipzig/master_thesis/analysis/tracks/"+y_oi+"/"+m_oi+"/"+d_oi+"/raw_Track_"+str(no)+".csv",index=False)

In [396]:
cell_data["flag"] = cell_data.cell
cell_data.cell = no

In [397]:
cell_data.to_csv("/Users/nicobader/Documents/Uni_Leipzig/master_thesis/analysis/tracks/"+y_oi+"/"+m_oi+"/"+d_oi+"/Track_"+str(no)+".csv",index=False)

In [399]:
import glob

glob.glob("/Users/nicobader/Documents/Uni_Leipzig/master_thesis/analysis/tracks/*")

['/Users/nicobader/Documents/Uni_Leipzig/master_thesis/analysis/tracks/2021',
 '/Users/nicobader/Documents/Uni_Leipzig/master_thesis/analysis/tracks/tracks.xlsx']