In [4]:
import pandas as pd
from standard_config import *

In [7]:
ci_data = pd.read_csv("/{}/HACI_bbox_data/haci-2010-05-24-bbox.dat".format(local_data_path),sep="\s+")

In [8]:
ausschnitt = ci_data[(ci_data.time >= "13:00") & (ci_data.time <= "14:00")]

In [9]:
zellen = ausschnitt[ausschnitt.t1 - ausschnitt.t0 > 3]

In [10]:
zellen

,date,time,id,flags,t0,t1,l00,l01,c00,c01,l0,l1,c0,c1
1852,2010-05-24,13:00,6952,0,156,165,159,162,493,495,159,162,493,495
1868,2010-05-24,13:00,6983,0,156,160,606,607,523,525,605,607,523,525
1869,2010-05-24,13:00,6984,0,156,163,610,611,533,534,610,612,532,534
1940,2010-05-24,13:20,7182,0,160,168,738,744,743,746,738,758,741,746
1941,2010-05-24,13:20,7183,0,160,166,743,749,664,668,736,749,664,695
1946,2010-05-24,13:25,7201,0,161,169,327,328,390,391,327,328,390,391
1953,2010-05-24,13:25,7230,0,161,178,691,698,522,556,655,699,522,672
1971,2010-05-24,13:30,7272,0,162,189,784,786,548,554,739,787,548,663
1975,2010-05-24,13:30,7279,0,162,166,823,826,637,640,820,827,637,658
2000,2010-05-24,13:40,7343,0,164,168,419,424,539,544,418,424,539,560
2002,2010-05-24,13:40,7351,0,164,175,458,463,333,340,441,463,333,391
2017,2010-05-24,13:45,7409,0,165,197,580,593,612,629,580,593,612,631
2020,2010-05-24,13:45,7421,0,165,179,664,665,833,834,645,666,831,891
2022,2010-05-24,13:45,7425,0,165,173,737,738,308,309,736,739,306,309
2035,2010-05-24,13:50,7452,0,166,188,415,419,831,837,406,459,775,900
2040,2010-05-24,13:50,7473,0,166,181,655,658,556,563,623,658,552,660
2055,2010-05-24,13:55,7521,0,167,171,778,779,607,609,772,780,607,623
2064,2010-05-24,14:00,7569,0,168,173,748,749,831,833,741,750,824,851